modLoader="javafml"
loaderVersion="[38,)"
license="GNU GPLv3"
issueTrackerURL="${github}/issues"
[[mods]]
modId="${id}"
version="${version}"
displayName="${name}"
displayURL="${github}"
logoFile="icon.png"
authors="${author}"
description="${description}"
[[dependencies.chunky]]
   modId="forge"
   mandatory=true
   versionRange="[41,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.chunky]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.19,1.20)"
   ordering="NONE"
   side="BOTH"
